import logging

import matplotlib.pyplot as plt
import torch

from . import FixedPointFinder as fp
from . import Task
from .FixedPointFinder.FixedPoints import FixedPoints
from .network import MotifNetwork

logger = logging.Logger(__name__)


def get_task_periods(
    model: MotifNetwork, task: Task, batch_size: int
) -> tuple[list[torch.Tensor], list[torch.Tensor], list[torch.Tensor], list[str]]:
    """Takes a network and task and returns the task period names input array,
    hidden states, and output array separated into task periods

    Parameters
    ----------
    model
        The network to pull the hidden state from
    task
        A task object to generate the input array and task periods
    batch_size
        The batch size, used to instantiate the task and network

    Returns
    -------
    input_state_periods
        The input array generated by the task split by task period
    hidden_state_periods
        The hidden state of the model split by task period
    output_state_periods
        The output of the model evaluating the input array split by task period
    task_periods
        A list of the task period names
    """
    input = task.get_input_array()
    h_0 = model.init_hidden(batch_size)
    with torch.no_grad():
        output, h_t = model(input, h_0)

    input_state_periods = [
        period.input_array.detach().cpu().numpy() for period in task.task_periods
    ]

    task_times = task.get_time_spans()
    hidden_state_periods = [
        h_t[period_times["start"] : period_times["end"]].cpu().detach().numpy()
        for period_times in task_times.values()
    ]
    output_state_periods = [
        output[period_times["start"] : period_times["end"]].cpu().detach().numpy()
        for period_times in task_times.values()
    ]
    task_periods = [f"{task.name}_{period.period_name}" for period in task.task_periods]
    return input_state_periods, hidden_state_periods, output_state_periods, task_periods


def find_fixed_points(
    model: MotifNetwork,
    input_state_periods: list,
    hidden_state_periods: list,
    output_state_periods: list,
    task_periods: list,
    output_dir: str,
    fpf_hp: dict = {"outlier_distance_scale": 2, "tol_q": 1e-3},
) -> tuple[list[plt.Figure], list[FixedPoints]]:
    """Finds fixed points for a particular network's hidden state and creates a plot
    for each time period.

    This function has the side effect that it will also save the figures to the
    ``output_dir``

    Parameters
    ----------
    model
        The network to evaluate fixed points for
    input_state_periods
        The input array generated by the task split by task period
    hidden_state_periods
        The hidden state of the model split by task period
    output_state_periods
        The output array of the model split by task period
    task_periods
        A list of the task period names
    output_dir
        The directory to save plots to
    fpf_hp, optional
        Any hyperparameters to use for the ``FixedPointFinder``.
        Bby default {'outlier_distance_scale': 2, 'tol_q': 1e-3}

    Returns
    -------
    fig
        A list of plots for the fixed point structure by time period
    f_points
        A list of ``FixedPoints`` objects by time period
    """
    figures = []
    f_points = []
    fpf = fp.FixedPointFinder(model, **fpf_hp)
    for i, (period_input, period_hidden_state, period_output, period) in enumerate(
        zip(
            input_state_periods,
            hidden_state_periods,
            output_state_periods,
            task_periods,
        )
    ):
        logger.info(f"Finding fixed points for {period}...")

        inputs = period_input.reshape(
            period_input.shape[0] * period_input.shape[1], period_input.shape[2]
        )
        state_trajectory = period_hidden_state.reshape(
            period_hidden_state.shape[0] * period_hidden_state.shape[1],
            period_hidden_state.shape[2],
        )
        period_output = period_output.reshape(
            period_output.shape[0] * period_output.shape[1],
            period_output.shape[2],
        )

        pca_index = (1, 2) if i == len(task_periods) - 1 else (0, 1)
        unique_fps, all_fps = fpf.find_fixed_points(state_trajectory, inputs)
        fig = fp.plot_fps(
            unique_fps, period_output, pca_index, period_hidden_state, title=period
        )
        figures.append(fig)
        f_points.append(unique_fps)
        logger.info(f"Saving plot to {output_dir}/{period}_fp_struct.png")
        fig.savefig(f"{output_dir}/{period}_fp_struct.png")
    return fig, f_points
