train:
  lr: 1.0e-3
  l2_terms: !!python/tuple [1.0e-6, 1.0e-6]
  batch_size: 64
  max_iter: 50000000
  clip_grad: True
  max_norm: 10
  task_kwargs:
    gamma: 0.2

model:
  hidden_size: 128
  nonlinearity: "softplus"
  private_noise_std: 0.05
  dt: 20
  tau: 100
  init_method: "diag"
  g: 0.8
  seed: 42